export const COLORS = {
  PRIMARY_BACKGROUND: "#EDCAEB",
  SECONDARY_BACKGROUND: "#ffe6fd",
  PRIMARY_TEXT: "#141414",
  PRIMARY_ACTIVE_BUTTON: "#ffffff",
  PRIMARY_DELETE_BUTTON: "#FFA8A8",
  PLACEHOLDER_TEXT: "#A1869F",
  INPUT_ERROR: "#A84850",
};
